name: epub_view
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
repository: https://github.com/ScerIO/packages.flutter/tree/main/packages/epub_view
issue_tracker: https://github.com/ScerIO/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+epub_view%22
version: 3.2.0
publish_to: none

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  equatable: ^2.0.5
  html: ^0.15.4
 
  scrollable_positioned_list_extended: ^0.3.9
  collection: ^1.17.1
  universal_file: ^1.0.0
  rxdart: ^0.27.7
  easy_debounce: ^2.0.3
  epubx:
   git:
      url: https://github.com/NedoPrograMax/epubx.dart
      ref: 2651c54e8831f65dc49e48af0715186721d0ceef
       
  flutter_html: 
   git:
      url: https://github.com/NedoPrograMax/flutter_html
      ref: 72af62b8791a867fa983614da0ab322300534f88
  flutter_svg: ^2.0.9

     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


